### ISSUE TITLE
Location of tooltip

### ISSUE THREAD

**Issue by PaulMcGuinness** [g1eb/calendar-heatmap#5]
When using this within nested <div>'s in a page, the tooltip doesn't take into account the parent div's top / height.

I used this jQuery, but I'm sure you can make it cleaner....

y + $(this).parent()[0].getBoundingClientRect().top - $(this).parent()[0].getBoundingClientRect().height

**Comment by g1eb** [comment]
Thanks for letting me know! I'll take a look :)

**Comment by g1eb** [comment]
I've updated tooltip position to take parent element into account as per your suggestions - thanks!

v0.0.14
