### ISSUE TITLE
Change the circle to square box in the in year view

### ISSUE THREAD

**Issue by adnanmayo** [g1eb/calendar-heatmap#6]
Is there any configuration to change the year view circles to rectangles? Or how it can be customized?

**Comment by g1eb** [comment]
there is no configuration for it but it's really easy to customize. Fork the repo and remove lines 488-493 in the [calendar-heatmap.js](https://github.com/g1eb/calendar-heatmap/blob/master/src/calendar-heatmap.js#L488) source file.

**Comment by g1eb** [comment]
Closing for now, feel free to reopen if you have questions and/or suggestions.
